version: "3.8"

services:
  agile-metrics-sonarqube:
    image: agile-metrics-sonarqube
    security_opt:
      - seccomp:unconfined
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SONAR_HOST=TBD_SONAR_HOST
      - CORE_METRICS_URL=TBD_CORE_METRICS_URL
